import {capilizeString} from './string'
import { language, ln, dir } from './language'

export const errors = {
  CWS: {
    0: {fa: 'خطایی از سمت سرور رخ داده است', en: ''},
    403: {fa: 'کاربر خارج شده است', en: 'User is logout'},
    //user

    100001: {fa: 'کاربر یافت نشد', en: 'Could not find user',},
    100002: {fa: 'نمی‌توان کاربر را فعال کرد', en: 'Could not activate user',},
    100003: {fa: 'هیچ گروهی با این نام یافت نشد', en: 'No group found with appropriate name',},
    100004: {fa: 'رمز عبور اشتباه است', en: 'Password is incorrect',},
    100005: {fa: 'کد بازیابی منقضی شده است', en: 'Reset code has been expired',},
    100006: {fa: 'ایمیل نمی‌تواند خالی باشد', en: 'Email can not be null',},
    100007: {fa: 'کاربر وجود دارد', en: 'User already exists',},
    100008: {fa: 'عملیات حمایت نمی‌شود', en: 'Operation is not allowed',},
    100009: {fa: 'ایمیل یافت نشد', en: 'Email does not exist',},
    1000010: {fa: 'ایمیل وجود ندارد', en: 'Email does not exist',},
    1000011: {fa: 'مقدار ورودی یافت نشد', en: 'Missing input value',},
    1000012: {fa: 'رمز عبور در مقدار ورودی وجود ندارد', en: 'Password is missing in input value',},
    1000013: {fa: 'کد بازیابی در مقدار ورودی وجود ندارد', en: 'ResetCode is missing in input value',},
    1000014: {fa: 'کد فعال‌سازی قرار داده نشده است', en: 'Unable to locate activationCode',},
    1000015: {fa: 'رمز عبور جاری در مقدار ورودی وجود ندارد', en: 'Current password is missing in input value',},
    1000016: {fa: 'رمز عبور جدید در مقدار ورودی وجود ندارد', en: 'New password is missing in input value',},
    1000017: {fa: 'رمز عبوری را انتخاب کنید که قبلا توسط شما انتخاب نشده باشد', en: 'Choose a password that you haven\'t previously used with this account',},
    1000018: {fa: 'نام در مقدار ورودی وجود ندارد', en: 'Name is missing in input value',},
    1000019: {fa: 'نام خانوادگی در مقدار ورودی وجود ندارد', en: 'Family is missing in input value',},
    1000020: {fa: 'اطلاعات کاربر مطابق الگو نیست', en: 'User information does not comply with pattern',},
    1000021: {fa: 'گروه نمی‌تواند خالی باشد', en: 'Group can not be null',},
    1000022: {fa: 'کاربر فعال شده است', en: 'User is already activated',},
    1000023: {fa: 'نام کاربری نمی‌تواند خالی باشد', en: 'Username can not be null',},
    1000024: {fa: 'کاربر پیدا نشد', en: 'User not found',},

    //hypervisor
    270001: {fa: 'وضعیت خالی برای سرور اصلی مورد قبول نیست', en: 'Hypervisor with null state is not supported'},
    270002: {fa: 'سرور اصلی پاسخ نداد', en: 'Hypervisor is not responding'},
    270003: {fa: 'سرور اصلی مناسبی پیدا نشد', en: 'Could not find a suitable Hypervisor'},
    270004: {fa: 'سرور اصلی در دسترس نیست', en: 'Hypervisor is not reachable'},
    270005: {fa: 'یا شبکه‌های فعالی وجود ندارند،یا سرور اصلی نیاز به پاکسازی دارد', en: 'Active domains or networks detected, Hypervisor needs to be cleared'},
    270006: {fa: 'در حال حاضر سرور منابع کافی ندارد', en: 'Hypervisor is out of resources at this time'},
    270007: {fa: 'وضعیت سرور اصلی بی‌نام است', en: 'Name missing in Hypervisor state statement'},
    270008: {fa: 'مقدار ورودی سرور اصلی غیر مجاز است', en: 'Invalid Hypervisor input value'},
    270009: {fa: 'نمی‌توان پاسخ سرور اصلی را پردازش کرد', en: 'Could not process Hypervisor response'},
    2700010: {fa: 'پاسخ درستی از سرور اصلی دریافت نشد', en: 'Could not parse Hypervisor response'},
    2700011: {fa: 'سرور اصلی محدودیت پردازنده دارد', en: 'Hypervisor is low on cpu'},
    2700012: {fa: 'سرور اصلی محدودیت حافظه دارد', en: 'Hypervisor is low on ram'},
    2700013: {fa: 'سرور اصلی وجود ندارد', en: 'Hypervisor does not exist'},
    2700014: {fa: 'ZfsArrayName موجود نیست', en: 'ZfsArrayName can not be null'},
    2700015: {fa: 'داده معتبر نیست', en: 'Invalid data'},
    2700016: {fa: 'خدمات موجود نیست', en: 'Service action is missing'},
    2700017: {fa: 'نوع خدمات موجود نیست', en: 'Service type action is missing'},

    //VPS
    280001: {fa: 'دسترسی به آخرین نام سیستمی سرور وجود ندارد', en: 'Could not obtain last VPS sysName'},
    280002: {fa: 'خطای غیر منتظره', en: 'Interrupted exception during VPS power-status update'},
    280003: {fa: 'نمی‌توان سرور اصلی را یافت', en: 'Could not find Hypervisor'},
    280004: {fa: 'کاربر به شبکه دسترسی ندارد', en: 'User has no access to network'},
    280005: {fa: 'برای حذف سرور باید آن را خاموش کنید', en: 'VPS can not be deleted while it is powered on'},
    280006: {fa: 'سرور مجازی روی سرور اصلی یافت نشد', en: 'Could not find VPS on Hypervisor'},
    280007: {fa: 'زمانی که سرور مجازی ساخته شده است نمی‌توان نوع سیستم عامل را تغییر داد', en: 'Could not change OS type once VPS is created'},
    280008: {fa: 'سایز حافظه، دیسک و تعداد پردازنده را زمانی‌که سرور مجازی روشن است نمی‌توان تغییر داد', en: 'Could not change disk size, ram, and cpu count while VPS is ON'},
    280009: {fa: 'سرور اصلی منابع کافی ندارد', en: 'Hypervisor does not have enough resources'},
    2800010: {fa: 'شما برای این عملیات مجوز ندارید', en: 'You are not allowed to perform this action'},
    2800011: {fa: 'وضعیت را نمی‌توان به‌روز رسانی کرد', en: 'Could not update state'},
    2800012: {fa: 'آی پی موجود نیست', en: 'Unable to identify a public network'},
    2800013: {fa: 'کارت شبکه تخصیص داده نشد، هم‌اکنون در حال استفاده است‬‎', en: 'Unable to allocate Nic. It is Already in use'},
    2800014: {fa: 'تعداد آی پی غیر مجاز است', en: 'Invalid IpCount'},
    2800015: {fa: 'کارت شبکه وجود ندارد', en: 'Nic does not exist'},
    2800016: {fa: 'کاربر وجود ندارد', en: 'User does not exist'},
    2800017: {fa: 'هویت کاربر تایید نشده است', en: 'Unauthenticated user'},
    2800018: {fa: 'مقصد نمی‌تواند خالی باشد‎', en: 'Target should not be empty'},
    2800019: {fa: 'نمی‌توان json ایجاد نمود', en: 'Could not create json'},
    2800020: {fa: 'فاقد مقدار ورودی', en: 'Missing input value'},
    2800021: {fa: 'خطا در عملیات روشن/خاموش سرور', en: 'PowerAction field is missing'},
    2800022: {fa: 'سرور مجازی وجود ندارد', en: 'VPS does not exist'},
    2800023: {fa: 'خطا در عملیات روشن/خاموش سرور', en: 'Can not switch VPS power state'},
    2800024: {fa: 'برای به‌روز رسانی سرور مجازی با وضعیت جدید از سرور اصلی تلاش کنید', en: 'Try to update VPS with new state from HYP'},
    2800025: {fa: 'اطلاعات کارت شبکه خالی است', en: 'Nic info is empty'},
    2800026: {fa: 'اطلاعات فضای اختیاری خالی است', en: 'Optional Storage info is empty'},
    2800027: {fa: 'به صورت پیش فرض شبکه خصوصی را نمی‌توانید انتخاب کنید', en: 'Private network could not be marked as default'},
    2800028: {fa: 'Capture Type یافت نشد', en: 'Unknown Capture Type'},
    2800029: {fa: 'سرور مجازی وجود ندارد', en: 'Could not find VPS'},
    2800030: {fa: 'سرور مجازی وجود دارد', en: 'VPS already Exists'},
    2800031: {fa: 'نام اجباری است', en: 'VPS name can not be empty'},
    2800032: {fa: 'سرور‌مجازی شما در حال حاضر پاک نشده است بنابراین ابتدا تمدید نمایید', en: 'Your VPS could not be deleted until you renew your VPS'},
    2800033: {fa: 'فیلد عملکرد خالی است', en: 'Action field is missing'},
    2800034: {fa: 'سرور مجازی خاموش است', en: 'VPS is off'},
    2800035: {fa: 'رمز عبور در مقدار ورودی وجود ندارد', en: 'Password is missing'},
    2800036: {fa: 'این شبکه در این موقعیت قابل انتخاب نیست', en: 'This network does not belong to current location'},
    2800036: {fa: 'ماشین را خاموش نمایید', en: 'VPS must be off'},
    2800037: {fa: 'مهاجرت با مشکل روبرو شد', en: 'Migration is falied'},
    2800038: {fa: 'منابع کافی برای ساخت سرور مجازی وجود ندارد', en: 'Not enough resource to create VPS'},
    2800039: {fa: 'امکان مهاجرت سرور‌مجازی وجود ندارد', en: 'Can not migrate VPS'},

    //network
    290001: {fa: 'نام سیستمی آخرین سرور مجازی یافت نشد', en: 'Could not get last network sysName'},
    290002: {fa: 'کاربر یافت نشد', en: 'Could not find network user'},
    290003: {fa: 'نمی‌توان شبکه را پیدا کرد', en: 'Could not find network'},
    290004: {fa: 'شبکه نباید بدون الگوی شبکه به طور مستقیم وارد شود', en: 'Network should not be inserted directly without network template'},
    290005: {fa: 'الگوی شبکه یافت نشد', en: 'Could not find network template'},
    290006: {fa: 'تعداد آی پی باید بزرگتر مساوی صفر باشد', en: 'IpCount should be larger than 0'},
    290007: {fa: 'نام شبکه خالی است', en: 'Network name field is null'},
    290008: {fa: 'الگوی شبکه باید قرار داده شود', en: 'NetworkTemplate should be set'},
    290009: {fa: 'بازه آی پی برای شبکه خصوصی یافت نشد', en: 'Could not find ip range for the given private network'},
    2900010: {fa: 'سرور‌های مجازی باید قبل از حذف از شبکه جدا شوند', en: 'All VPSs must be detached from network before deletion'},
    2900011: {fa: 'کاربر تایید هویت نشده است', en: 'Unauthenticated user'},
    2900012: {fa: 'تنها شبکه خصوصی می‌تواند ایجاد شود', en: 'Only private network can be created'},
    2900013: {fa: 'فقط امکان ساخت شبکه خصوصی وجود دارد', en: 'You can only insert private network'},

    //nic
    300001: {fa: 'کارت شبکه اصلی یافت نشد', en: 'Unable to delete primary nic'},

    //subnet
    310001: {fa: 'زمانی‌که زیرشبکه‌ها تداخل دارند نمی‌توان زیرشبکه ایجاد کرد', en: 'Cloud not insert subnet due to overlapping subnets'},
    310002: {fa: 'زیرشبکه نمی‌تواند به‌روز رسانی شود', en: 'Subnet should not be updated'},
    310003: {fa: 'Netmask غیر مجاز است', en: 'Netmask is invalid'},
    310004: {fa: 'آی پی غیر مجاز است', en: 'Ip is invalid'},
    310005: {fa: 'زیرشبکه آی پی‌ها را نمی‌توان تخصیص داد', en: 'Subnet could not allocate ips'},

    //hypervisorApiAdapter
    320001: {fa: 'خطا وجود دارد', en: 'Interrupted Exception occurred'},
    320002: {fa: 'خطا در اجرای عملیات', en: 'Execution Exception occurred'},
    320003: {fa: 'در زمان مناسب پاسخی دریافت نشد', en: 'Timeout Exception occurred'},
    320004: {fa: 'فرستادن درخواست حذف به آدرس اينترنتي', en: 'DELETE request to URI is sent'},
    320005: {fa: 'فرستادن درخواست ایجاد به آدرس اينترنتي', en: 'POST request to URI is sent'},
    320006: {fa: 'اطلاعات خالی است', en: 'Data can not be empty'},
    320007: {fa: 'فرستادن درخواست به‌روز رسانی به آدرس اينترنتي', en: 'PUT request to URI is sent'},
    320008: {fa: 'نمی‌توان سرور‌های مجازی را لیست کرد', en: 'Could not list VPSs'},
    320009: {fa: 'لیست نام سرورهای مجازی یافت نشد', en: 'Could not get list of VPSs name'},
    3200010: {fa: 'سرور مجازی را نمی‌توان به‌روز رسانی کرد', en: 'Can not update  VPS'},
    3200011: {fa: 'سایز پردازنده نمی‌تواند بیشتر از سه برابر زمانی که سرور مجازی روشن است شود', en: 'CPU size can not be more than 3 times when VPS is powered on'},
    3200012: {fa: 'سایز حافظه نمی‌تواند بیشتر از سه برابر شود زمانی که وی ام روشن است', en: 'Memory size can not be more than 3 times when VPS is powered on'},
    3200013: {fa: 'خطا در خواندن hyp brush json وجود دارد', en: 'Error attempt reading hyp brush json'},
    3200014: {fa: 'بدون کارت شبکه نمی‌توان سرور مجازی ساخت', en: 'Could not create VPS without Nics'},
    3200015: {fa: 'نمی‌توان سرور مجازی ساخت', en: 'Can not create  VPS'},
    3200016: {fa: 'حالت سرور مجازی قابل تغییر نیست', en: 'Cannot switch VPS from current power state'},
    3200017: {fa: 'وضعیت سرور مجازی را نمی‌توان روی سرور اصلی تغییر داد', en: 'Can not switch VPS state on Hyp'},
    3200018: {fa: 'وضعیت پاور سرور مجازی را نمی‌توان قرار داد', en: 'Could not set VPS power status'},
    3200019: {fa: 'سرور مجازی را نمی‌توان از سرور اصلی پاک کرد', en: 'Could not Delete VPS on HYP'},
    3200020: {fa: 'وضعیت پاور سرور مجازی را نمی‌توان بدست آورد', en: 'Could not obtain VPS power status'},
    3200021: {fa: 'به سرورهای اصلی نمی‌توان اطلاع داد', en: 'Could not inform hypervisors'},
    3200022: {fa: 'وصل سرورهای اصلی به سیستم موفقیت‌آمیز نبود', en: 'Assigning Hyp To Cws was not successfull'},
    3200023: {fa: 'قطع اتصال سرور اصلی از سیستم موفقیت‌آمیز نبود', en: 'UnAssigning Hyp from Cws was not successfull'},
    3200024: {fa: 'وضعیت سرور اصلی را نمی‌توان بدست آورد', en: 'Could not obtain Hypervisor state'},
    3200025: {fa: 'وضعیت سرور مجازی یافت نشد', en: 'Can not get VPS status'},
    3200026: {fa: 'نمی‌توان json برای دیسک ایجاد نمود', en: 'Could not create json for disk'},
    3200027: {fa: 'حافظه جدید را نمی‌توان به سرور مجازی وصل کرد', en: 'Attaching new disk to VPS failed'},
    3200028: {fa: 'حافظه را از سرور مجازی نمی‌توان پاک کرد', en: 'Could not delete disk from VPS'},
    3200029: {fa: 'از سرور مجازی نمی‌توان عکس گرفت', en: 'Could not take screenshot from VPS'},
    3200030: {fa: 'از سرور مجازی نمی‌توان عکس گرفت', en: 'Could not take screenshot from VPS'},
    3200031: {fa: 'از سرور نمی‌توان عکس گرفت', en: 'Could not capture VPS screen'},
    3200032: {fa: 'از سرور نمی‌توان عکس گرفت', en: 'Screencasting Failed'},
    3200033: {fa: 'نمی‌توان رمز عبور را تغییر داد', en: 'Could not change password'},
    3200034: {fa: 'سرور مجازی را نمی‌توان از صف پاک کرد', en: 'Could not Delete VPS on Queue'},
    3200035: {fa: 'تگ نمی‌تواند خالی باشد', en: 'Tag cannot be empty'},
    3200036: {fa: 'سرور‌مجازی باید خاموش باشد', en: 'VPS must be off'},
    3200037: {fa: 'ابتدا سرویس libvirtd را روشن نمایید', en: 'First start libvirtd service'},

    //NetworkFacade
    330001: {fa: 'شبکه پیدا نشد', en: 'Could not find network'},
    330002: {fa: 'سرور مجازی یافت نشد', en: 'Could not find VPS'},
    330003: {fa: 'زیرشبکه‌های موجود برای آی پی‌ها وجود ندارد', en: 'There are no subnets available for IPs'},
    330004: {fa: 'آی پی را نمی‌توان پاک کرد', en: 'Can not remove IP'},
    330005: {fa: 'آی پی کافی برای کارت شبکه وجود ندارد', en: 'There are not enough ips for current nic'},
    330006: {fa: 'آی پی‌های کافی روی شبکه وجود ندارد', en: 'There are not enough IPs in the network'},
    330007: {fa: 'خارج از بازه برای شبکه عمومی', en: 'Out of range for public network'},
    330008: {fa: 'آی پی تخصیص نیافته پیدا شد', en: 'Unallocated IP found'},
    330009: {fa: 'کارت شبکه اصلی را نمی‌توانید پاک کنید', en: 'Deleting primary NIC is not allowed'},

    //NetworkMediator
    340001: {fa: 'اطلاعات کارت شبکه نمی‌تواند خالی باشد', en: 'Nic info can not be null'},
    340002: {fa: 'اطلاعات کارت شبکه نمی‌تواند خالی باشد', en: 'Nic info network can not be null'},
    340003: {fa: 'شبکه عمومی خالی است', en: 'Public network empty'},
    340004: {fa: 'شبکه باید عمومی باشد', en: 'Network should be public'},
    340005: {fa: 'سرور مجازی یا شبکه نمی‌تواند خالی باشد', en: 'VPS/Network cannot be null'},
    340006: {fa: 'قبل از استفاده از سرور مجازی آن را ثبت نام کنید', en: 'Register VPS before using it'},
    340007: {fa: 'قبل از استفاده از اطلاعات کارت شبکه آن را ثبت نام کنید', en: 'Register NicInfo before using it'},

    //privateNetwork
    350001: {fa: 'سرورهای مجازی باید قبل از حذف از شبکه جدا شوند', en: 'All VPSs must be detached from network before deletion'},
    350002: {fa: 'تعداد آی پی باید بزرگتر مساوی صفر باشد', en: 'IP count should be larger than zero'},
    350003: {fa: 'نام شبکه وجود ندارد', en: 'Network should have a name'},
    350004: {fa: 'الگوی شبکه باید قرار داده شود', en: 'Network template should be set'},
    350005: {fa: 'نمی‌توان بازه ی آی پی برای شبکه خصوصی پیدا کرد', en: 'Could not find ip range for the given private network'},
    350006: {fa: 'تعداد آی پی را نمی‌توان تغییر داد', en: 'Can not change IP count'},
    350007: {fa: 'نام سیستمی را نمی‌توان تغییر داد', en: 'Can not change sysName'},

    //publicnetwork
    360001: {fa: 'شبکه یافت نشد', en: 'Could not find network'},
    360002: {fa: 'تعداد آی پی باید بزرگتر مساوی صفر باشد', en: 'IpCount should be more than zero'},
    360003: {fa: 'نام شبکه وجود ندارد', en: 'Network should have a name'},
    360004: {fa: 'الگوی شبکه باید قرار داده شود', en: 'NetworkTemplate should be set'},
    360005: {fa: 'تعداد آی پی را نمی‌توان تغییر داد', en: 'Can not change ipCount'},
    360006: {fa: 'نام سیستمی را نمی‌توان تغییر داد', en: 'Can not change sysName'},
    360007: {fa: 'سرورهای مجازی باید قبل از حذف از شبکه جدا شوند', en: 'All VPSs must be detached from network before deletion'},

    //beforeinsertnetworktemplatevalidator
    370001: {fa: 'بازه آی پی وجود دارد', en: 'IP Range Exists'},
    370002: {fa: 'نام الگوی شبکه وجود دارد', en: 'NetworkTemplate name already Exists'},
    370003: {fa: 'الگوی شبکه عمومی باید شامل Netmask عمومی و زیرشبکه عمومی باشد', en: 'Public network template should contain publicNetmask and publicSubnet'},

    //beforeinsertnetworkvalidator
    380001: {fa: 'نام شبکه وجود دارد', en: 'Network name already Exists'},
    380002: {fa: 'فقط یک شبکه عمومی می‌توان ساخت', en: 'Public network already exists'},

    //beforeinsertvmvalidator
    390001: {fa: 'سرور مجازی وجود دارد', en: 'VPS already exists'},
    390002: {fa: 'گام افزایش حافظه غیر مجاز است', en: 'Invalid increment step for ram'},
    390003: {fa: 'گام افزایش برای هسته‌های پردازنده غیر مجاز است', en: 'Invalid increment step for cpuCores'},
    390004: {fa: 'گام افزایش برای دیسک غیر مجاز است', en: 'Invalid increment step for primaryDisk'},
    390005: {fa: 'شما نمی‌توانید بیشتر از چهل عدد سرور مجازی روی سرور اصلی بسازید', en: 'Hyp VPS limit reached, you can not add more than 40 VPSs on a Hyp'},
    390006: {fa: 'شبکه نمی‌تواند خالی باشد', en: 'Network should not be empty'},
    390007: {fa: 'تعداد آی پی‌های شبکه باید بزرگتر مساوی صفر باشد', en: 'Network IP count should be greater than zero'},
    390008: {fa: 'آی پی کافی برای تخصیص دادن به شبکه عمومی وجود ندارد', en: 'There are not enough IP to allocate to public network'},
    390009: {fa: 'تعداد هسته‌های پردازنده باید بزرگتر مساوی یک باشد', en: 'CPU cores count should be greater than 1'},
    3900010: {fa: 'حافظه باید بزرگتر مساوی یک گیگا بایت باشد', en: 'Ram should be greater than 1GB'},
    3900011: {fa: 'سایز دیسک باید بزرگتر مساوی ده گیگا بایت باشد', en: 'PrimaryDisk size should be greater than 10GB'},
    3900012: {fa: 'تعداد هسته‌های پردازنده باید کوچکتر مساوی بیست و دو باشد', en: 'CpuCores count should be less than 22'},
    3900013: {fa: 'حافظه باید کوچکتر مساوی شصت و شش گیگا بایت باشد', en: 'Ram should be less than 66GB'},
    3900014: {fa: 'سایز حافظه باید کوچکتر مساوی دویست وپنجاه گیگا بایت باشد', en: 'PrimaryDisk size should be less than 250GB'},
    3900015: {fa: 'نام اجباری است', en: 'VPS name can not be empty'},

    //beforeinsertuservalidator
    400001: {fa: 'کاربر وجود دارد', en: 'User already exists'},

    //config
    410001: {fa: 'تنظیمات چک شود', en: 'Check web server config unpack war'},
    410002: {fa: 'خطای ورودی خروجی', en: 'I/O Exception'},

    //vmUsage
    420001: {fa: 'پارامترها غیر مجاز است', en: 'Invalid parameters'},
    420002: {fa: 'پلن یا کاربر یافت نشد', en: 'Unable to find plan/user'},
    420003: {fa: 'لیست قیمت‌های سرور مجازی یافت نشد', en: 'Could not find VPS priceList'},


    //vmbill
    430001: {fa: 'پلن نمی‌تواند خالی باشد', en: 'Plan can not be null'},
    430002: {fa: 'پلن مورد نظر یافت نشد', en: 'Could not find plan'},
    430003: {fa: 'قبلا برای این سرور مجازی فاکتور صادر شده است', en: 'Invoice is already generated for this VPS'},
    430004: {fa: 'فاکتور پرداخت شده قابل حذف نیست', en: 'Can not delete paid invoice'},
    430005: {fa: 'تعداد خرید پرداخت نشده بیش از حدمجاز است', en: 'Can not create more unpaid VmBill'},
    430006: {fa: 'سرور مجازی ایجاد شده قابل حذف نیست', en: 'Can not delete existed VPS'},
    430007: {fa: 'هیچ صورتحسابی وجود دارد', en: 'There is no bill'},
    430008: {fa: 'صورتحساب سرور مجازی را نمی‌توان یافت', en: 'Vm bill can not be found'},
    430009: {fa: 'کد مقدار ندارد', en: 'Promo code is null'},
    4300010: {fa: 'محل مورد نظر یافت نشد', en: 'Could not find location'},
    4300011: {fa: 'هایپروایزر وجود ندارد', en: 'Hypervisor can not be found'},
    4300012: {fa: 'لطفا هایپروایزر را انتخاب نمایید', en: 'Please select a hypervisor'},
    4300013: {fa: 'داده معتبر نیست', en: 'Invalid data'},
    4300014: {fa: 'تغییر امکان‌پذیر نیست', en: 'Update is not possible'},
    4300015: {fa: 'شبکه تکراری دارد', en: 'Redundant network item'},
    4300016: {fa: 'سیستم عامل صحیح نیست', en: 'Operating System is not valid'},
    4300017: {fa: 'حداقل منابع نیاز است', en: 'Minimum Resource is required'},
    4300018: {fa: 'حداقل منابع تعریف نشده است', en: 'Minimum Resource is not defined'},
    4300019: {fa: 'تا پایان زمان بندی استفاده نمی‌توانید عملیات را انجام دهید', en: 'You can\'t do the operation until end of idle time'},
    4300020: {fa: 'Key Id نمی‌تواند خالی باشد', en: 'Key Id can\'t be empty'},
    4300021: {fa: 'Key Id اشتباه است', en: 'Key Id is wrong'},
    4300022: {fa: 'سرور باید خاموش باشد', en: 'VPS Can\'t be on'},
    4300023: {fa: 'این ویژگی در سیستم‌های ویندوزی امکان‌پذیر نیست', en: 'VPS Can\'t be Windows'},
    4300024: {fa: 'خطا در پین کردن سرور مجازی', en: 'Can not assign hyp to VPS'},
    4300025: {fa: 'لطفا نام فایل را وارد نمایید', en: 'Please provide a file name'},
    4300026: {fa: 'خطا در اجرای عملیات', en: 'Operation error'},
    4300027: {fa: 'ضروری', en: 'Required'},
    4300028: {fa: 'نوع', en: 'Type'},
    4300029: {fa: 'الگو', en: 'Pattern'},
    4300030: {fa: 'نام ایزو وجود دراد', en: 'ISO file name is exists'},

    //payment
    90001: {fa: 'لطفا جهت تمدید سرور‌مجازی خود اقدام نمایید', en: 'Renew your Cloud VPS'},

    //invoice
    240001: {fa: 'نوع محصول اشتباه است', en: 'Incorrect Product Category'},
    240002: {fa: 'اعتبار کافی نیست', en: 'Insufficient Credit'},
    240003: {fa: 'شناسه اجباری است', en: 'ID is Mandatory'},
    240004: {fa: 'داده نا معتبر', en: 'Invalid ID'},
    240005: {fa: 'سرور را باید خاموش کنید', en: 'Shutdown the server'},
    240006: {fa: 'نوع پرداخت الزامی است', en: 'Insufficient data'},

    //vmBackup
    250001: {fa: 'ابتدا libvirtd را start نمایید', en: 'First start libvirtd'},
    430001: {fa: 'در هر لحظه فقط یک نسخه پشتیبان می‌تواند داشته باشد', en: 'VPS can only have one backup at a time'},

    //vmRule
    440001: {fa: 'پروتکل تکراری', en: 'Rule is duplicate'},
    440002: {fa: 'پروتکل ضروری', en: 'Rule is required'},
    440003: {fa: 'پروتکل نوع', en: 'Rule type'},
    440004: {fa: 'پروتکل الگو', en: 'Rule pattern'},
    440005: {fa: 'جهت ضروری', en: 'Direction is required'},
    440006: {fa: 'نوع جهت', en: 'Direction type'},
    440007: {fa: 'جهت الگو', en: 'Direction pattern'},
    440008: {fa: 'dstportstart ضروری', en: 'Dstportstart is required'},
    440009: {fa: 'نوع dstportstart', en: 'Dstportstart type'},
    4400010: {fa: 'فیلتر شبکه ضروری', en: 'Network filter is required'},
    4400011: {fa: 'نوع فیلتر شبکه', en: 'Network filter type'},
    4400012: {fa: 'نوع عمل', en: 'Action type'},
    4400013: {fa: 'الگوی عمل', en: 'Action pattern'},
    4400014: {fa: 'شماره شناسایی ضروری', en: 'Id is required'},
    4400015: {fa: 'نوع شماره شناسایی', en: 'Id type'},
    4400016: {fa: 'داده نامعتبر', en: 'Invalid data'},
  },
  CFS: {
    0: {fa: 'خطایی از سمت سرور رخ داده است', en: ''},
    403: {fa: 'کاربر خارج شده است', en: 'User is logout'},

    // document
    10001: {fa: 'تفکیک کننده نمی‌تواند خالی باشد', en: 'Discriminator can not be null'},
    10002: {fa: 'تفکیک کننده غیر مجاز است فقط برای فایل یا پوشه می‌توان از این سرویس استفاده نمود', en: 'Invalid discriminator,only folder/File can use this service'},
    10003: {fa: 'پوشه خانه پیدا نشد', en: 'Can not find Home folder'},
    10004: {fa: 'پوشه پدر پیدا نشد', en: 'Could not find parent'},
    10005: {fa: 'شما نمی‌توانید فایل یا پوشه را در پاک شده‌ها آپلود نمایید', en: 'You can not upload a file/folder to trash'},
    10006: {fa: 'تنها پوشه یا پوشه‌ها را می‌توانید به لیست مورد علاقه اضافه نمایید', en: 'Only folder(s) can be favourite'},
    10007: {fa: 'سرویس از رده خارج است', en: 'Deprecated Service'},
    10008: {fa: 'شما نمی‌توانید به پاک شده‌ها جابه جایی داشته باشید', en: 'You can not move to trash'},
    10009: {fa: 'سندی با این نام در مقصد وجود دارد', en: 'Document with the same name already exists in this target'},
    100010: {fa: 'برای اشتراک گذاری خودکار نقض محدودیت وجود دارد', en: 'Constraint Violation while Auto-Share'},
    100011: {fa: 'ورودی غیر مجاز است', en: 'Invalid input'},
    100012: {fa: 'سندی وجود دارد که توسط شخص دیگری ساخته شده است', en: 'There is a document created by another owner'},
    100013: {fa: 'عملیات حمایت نمی‌شود', en: 'Unsupported Operation'},
    100014: {fa: 'شناسه نمی‌تواند خالی باشد', en: 'Ids can not be null'},
    100015: {fa: 'شما صاحب کل ساختار نیستید', en: 'You are not the owner of whole structure'},
    100016: {fa: 'سندی وجود دارد که در پوشه به اشتراک گذاشته شده قرار گرفته است', en: 'There is a document located under a shared folder'},
    100017: {fa: 'شما نمی‌توانید سند را به پوشه‌ای که در آن پوشه سندی با آن نام یا نوع وجود دارد بازگردانید', en: 'Can not restore a document to a folder when the folder contains another document with the same name and type'},
    100018: {fa: 'شامل یک آیتم به اشتراک گذاشته شده است  ', en: 'Contains a shared item'},
    100019: {fa: 'نمی‌توان جابه جا نمود', en: 'Can not move'},
    100020: {fa: 'نمی‌تواند هم برای نام و هم برای مسیر اعمال شود', en: 'Can not apply both name and path together'},
    100021: {fa: 'لطفا نام یا مسیر را وارد نمایید', en: 'Please provide name or path'},
    100022: {fa: 'برای آیتم‌های پاک شده غیر فعال است', en: 'Disable for trashed items'},
    100023: {fa: 'برای آیتم‌های به اشتراک گذاشته غیر فعال است', en: 'Disable for shared items'},
    100024: {fa: 'سرویس حمایت نمی‌شود', en: 'Unsupported Service'},
    100025: {fa: 'فایل انتخاب نمایید', en: 'Choose a File'},
    100026: {fa: 'عکس انتخاب نمایید', en: 'Choose an Image'},
    100027: {fa: 'ایمیل کاربر نمی‌تواند خالی باشد', en: 'User email can not be null'},
    100028: {fa: 'برای این نوع فایل پیش نمایشی وجود ندارد', en: 'This file type has no preview'},
    100029: {fa: 'نمی‌توانید به فایل جابه جایی داشته باشید', en: 'Can not move to file'},
    100030: {fa: 'نمی‌توانید جابه جایی داشته باشید', en: 'Move not allowed'},
    100031: {fa: 'سندی پیدا نشد', en: 'No documents found'},
    100032: {fa: 'سند موجود است', en: 'Document Already Exists'},
    100033: {fa: 'شما نمی‌توانید یک فایل را با خودتان به اشتراک بگذارید', en: 'You can not share a file with yourself'},
    100034: {fa: 'نام فایل شامل کاراکترهای غیر مجاز است', en: 'Invalid file name'},
    100035: {fa: 'شما مجوز این کار را ندارید', en: 'Please upgrade your plan to use this feature'},
    100036: {fa: 'فضای خالی موجود نیست', en: 'You do not have enough free space'},
    100037: {fa: 'پوشه وجود دارد نام دیگری انتخاب نمایید', en: 'Folder Already Exists Choose another name'},
    100038: {fa: 'فایل وجود دارد', en: 'File already exists'},
    100039: {fa: 'توکن نا معتبر', en: 'Invalid Sync Token'},
    100040: {fa: 'فایل‌های انتخابی در یک سرور موجود نیستندِ تا یکی شدن شکیبا باشید یا اقدام به دانلود جداگانه هر فابل نمایید', en: 'Some Files are No In Current Server'},
    100041: {fa: 'حذف امکان‌پذیر نیست', en: 'Delete is impossible'},
    100042: {fa: 'مالک فایل است', en: 'Owner of the file'},
    100043: {fa: 'نمی‌توانید یک فایل بایگانی ایجاد نمایید', en: 'Can not create a archive file'},
    100044: {fa: 'نوع فایل الزامی است', en: 'The file type is mandatory'},
    100045: {fa: 'نام نمی‌تواند خالی باشد', en: 'Name cannot be empty'},
    100046: {fa: 'ایمیل اشتراک درست نیست', en: 'Invalid share data'},

    // publicAccess
    20001: {fa: 'نتیجه‌ای یافت نشد', en: 'Result not Found'},
    20002: {fa: 'کاربر پیدا نشد', en: 'User not Found'},
    20003: {fa: 'پوشه پیدا نشد', en: 'Folder not found'},
    20004: {fa: 'فایل مورد نظر شما توسط مالک آن از دسترس خارج شده است', en: 'The requested file has been made unaccessible by it\'s owner.'},
    20005: {fa: 'مسیر انتخابی اشتباه است', en: 'Unsupported Service'},
    20006: {fa: 'برای آیتم‌های پاک شده غیر فعال است', en: 'Disable for trashed items'},
    20007: {fa: 'UUID نمی‌تواند خالی باشد', en: 'UUID can not be null'},
    20008: {fa: 'برای حالت سایت غیر فعال است', en: 'Disable pg mode'},
    20009: {fa: 'فایل انتخاب نمایید', en: 'Choose a File'},
    200010: {fa: 'برای این نوع فایل پیش نمایشی وجود ندارد', en: 'This file type has no preview'},
    200011: {fa: 'ترافیک شما به پایان رسیده است', en: 'You have exceeded your bandwidth'},
    200012: {fa: 'UUID نامعتبر است', en: 'Invalid UUID'},
    200013: {fa: 'نام دامنه خالی است', en: 'Domain is empty'},
    200014: {fa: 'مسیر خالی است', en: 'Path is empty'},
    200015: {fa: 'دامنه معتبر نیست', en: 'Domain is not valid'},

    140001: {fa: 'فایل موجود است', en: 'File already exists'},

    30001: {fa: 'در خواست مورد نظر یافت نشد', en: 'Constraint Violation while Auto-Share'},

    // file
    40001: {fa: 'عملیات موفقیت‌آمیز نبود لطفا دوباره تلاش نمایید', en: 'Could not store temp due I/O exception'},
    40002: {fa: 'عملیات موفقیت‌آمیز نبود لطفا دوباره تلاش نمایید', en: 'Could not store temp files due unknown details'},
    40003: {fa: 'کپی فایل غیر فعال است', en: 'Unable to copy File'},
    40004: {fa: 'آپلود موفقیت‌آمیز بود', en: 'Upload successful'},
    40005: {fa: 'فایل آلوده است', en: 'File is infected'},
    40006: {fa: 'سند یافت نشد', en: 'Document not found'},
    40007: {fa: 'صاحب فایل نمی‌تواند خالی باشد', en: 'Owner can not be empty'},

    // download
    50001: {fa: 'فایل انتخاب نمایید', en: 'Choose a File'},
    50002: {fa: 'فشرده کردن فایل‌ها', en: 'Compressing Files'},
    50003: {fa: 'نمی‌توان فایل‌ها را فشرده نمود', en: 'Could not compress Files'},
    50004: {fa: 'فشرده سازی فایل‌ها', en: 'Files compressed to {0}'},
    50005: {fa: 'تعدادی از فایل‌ها در سرور موجود نیستند', en: 'Some Files are Not In Current Location'},

    // fileSystemRepository
    60001: {fa: 'سند خالی نمی‌تواند قرار بگیرد', en: 'Can not locate null document'},
    60002: {fa: 'در خواست قابل تشخیص نیست', en: 'Unable to distinguish entity'},
    60003: {fa: 'عوض کردن نام پوشه غیر فعال است', en: 'Unable to rename folder'},
    60004: {fa: 'پاک کردن حافظه موقت غیر فعال است', en: 'Unable to clean temp'},
    60005: {fa: 'MIME TYPE قابل حدس نیست', en: 'Unable to guess MIME TYPE'},
    60006: {fa: 'سند را نمی‌توان پاک کرد', en: 'Could not delete document'},

    // folder
    70001: {fa: 'تطابق مسیر پوشه با مسیر', en: 'Match folder path with path'},

    // tag
    80001: {fa: 'نام بر چسب نمی‌تواند خالی باشد', en: 'Tag name can not be null'},

    //user
    90001: {fa: 'جهت تمدید حساب خود اقدام نمایید', en: 'Renew your Cloud Storage'},
    100001: {fa: 'کاربر یافت نشد', en: 'Could not find user'},
    100002: {fa: 'کاربر قابل فعال شدن نیست', en: 'Could not activate user'},
    100003: {fa: 'هیچ گروهی با این نام یافت نشد', en: 'No group found with name'},
    100004: {fa: 'رمز عبور اشتباه است', en: 'Password is incorrect'},
    100005: {fa: 'کد بازیابی منقضی شده است', en: 'Reset code has been expired'},
    100006: {fa: 'ایمیل نمی‌تواند خالی باشد', en: 'Email can not be null'},
    100007: {fa: 'کاربر وجود دارد', en: 'User Already Exists'},
    100008: {fa: 'کاربر وجود ندارد', en: 'User does not exist'},
    100009: {fa: 'ایمیل قرار داده نشده است', en: 'Unable to locate email'},
    1000010: {fa: 'ایمیل وجود ندارد', en: 'Email does not exist'},
    1000011: {fa: 'مقدار ورودی یافت نشد', en: 'Missing input value'},
    1000012: {fa: 'رمز عبور در مقدار ورودی وجود ندارد', en: 'Password is missing in input value'},
    1000013: {fa: 'کد بازیابی در مقدار ورودی وجود ندارد', en: 'ResetCode is missing in input value'},
    1000014: {fa: 'کد فعال‌سازی قرار داده نشده است', en: 'Unable to locate activationCode'},
    1000015: {fa: 'رمز عبور جاری در مقدار ورودی وجود ندارد', en: 'CurrentPassword is missing is input value'},
    1000016: {fa: 'رمز عبور جدید در مقدار ورودی وجود ندارد', en: 'NewPassword is missing in input value'},
    1000017: {fa: 'رمز عبوری را انتخاب نمایید که قبلا توسط شما انتخاب نشده باشد', en: 'Choose a password that you haven\'t previously used with this account.'},
    1000018: {fa: 'نام در مقدار ورودی وجود ندارد', en: 'Name is missing in input value'},
    1000019: {fa: 'نام خانوادگی در مقدار ورودی وجود ندارد', en: 'Family is missing in input value'},
    1000020: {fa: 'اطلاعات کاربر مطابق الگو نیست', en: 'User information does not comply with pattern'},
    1000021: {fa: 'گروه نمی‌تواند خالی باشد', en: 'Group can not be null'},
    1000022: {fa: 'عملیات حمایت نمی‌شود', en: 'Unsupported Operation'},
    1000023: {fa: 'پلن در مقدار ورودی یافت نشد', en: 'Plan object is missing in input value'},
    1000024: {fa: 'شناسه در مقدار ورودی پلن یافت نشد', en: 'Id is missing in plan input value'},
    1000025: {fa: 'پلن یافت نشد', en: 'Could not find plan'},
    1000026: {fa: 'پلن انتخاب شده پلن جاری است', en: 'The selected plan is your current plan'},
    1000027: {fa: 'پلن انتخاب شده پلن رایگان است شما نمی‌توانید آن را انتخاب نمایید', en: 'The selected plan is free,you can\'t change plan to free'},
    1000028: {fa: 'نام کاربری نمی‌تواند خالی باشد', en: 'Username can not be null'},
    1000029: {fa: 'کاربر فعال شده است', en: 'User is already activated'},
    1000030: {fa: 'تا پایان پلن شما نمی‌توانید پلن پایین تر انتخاب نمایید', en: 'Downgrade is not supported'},
    1000031: {fa: 'قیمت نمی‌تواند خالی باشد', en: 'PriceInfo can not be null'},
    1000032: {fa: 'بازه زمانی ارسال پیام کمتر از حد مجاز است', en: 'Date interval is less than supported'},
    1000033: {fa: 'مشکل در ارسال پیام', en: 'Sms sending problem'},
    1000034: {fa: 'کد معتبر نیست', en: 'Verification Code is Not Valid'},
    1000035: {fa: 'نام کاربری و گذر واژه اجباری است', en: 'Username Password Is Needed'},
    1000036: {fa: 'دفعات ارسال پیامک از میزان مجاز بیشتر شده است، لطفا جهت رفع مشکل با پشتیبانی تماس بگیرید', en: 'SMS Verification Attempt'},
    1000037: {fa: 'ارسال پیامک با مشکل روبرو شد', en: 'SMS Sending Problem'},
    1000038: {fa: 'کد تایید شماره موبایل شما در سایت', en: 'SMS Default Text'},
    1000039: {fa: 'شماره موبایل قبلا ثبت شده است', en: 'Mobile Exist'},
    1000040: {fa: 'کاربر یک دامنه فعال دارد', en: 'One Domain Allowable ProPlan'},
    1000043: {fa: 'رمز عبور اجباری است', en: 'Password Is Empty'},
    1000044: {fa: 'گروه پیدا نشد', en: 'Not Found Group'},
    1000045: {fa: 'احراز هویت برای کاربر تعریف نشده است', en: 'Authentication is not defined for the user'},

    // SQL FUNCTIONS ERROR CODE
    110001: {fa: 'پوشه پدر وجود ندارد', en: 'Parent folder does not exist'},
    110002: {fa: 'سند به اشتراک گذاشته شده نمی‌تواند دوباره به اشتراک گذاشته شود', en: 'A shared document can not be shared again'},
    110003: {fa: 'سند پیدا نشد', en: 'Document not found'},
    110004: {fa: 'مقصد پیدا نشد', en: 'Target not found'},
    110005: {fa: 'نمی‌توان به پوشه‌ای که به اشتراک گذاشته شده کپی کرد', en: 'Can not copy to shared folder'},
    110006: {fa: 'کاربر دسترسی ندارد', en: 'User has no such access'},
    110007: {fa: 'سند مشابه در مقصد وجود دارد', en: 'A similar document already exists in destination'},
    110008: {fa: 'جابجائی غیر مجاز است', en: 'Illegal move'},
    110009: {fa: 'نمی‌توان سند را درون پوشه به اشتراک گذاشته شده قرار داد', en: 'Can not embed the document into a shared folder'},
    1100010: {fa: 'کاربر صاحب کل ساختار سند نیست', en: 'User is not the owner of whole document tree'},
    1100011: {fa: 'نمی‌توان سندی که به اشتراک گذاشته شده به پوشه‌ای که به اشتراک گذاشته شده جابه جا کرد', en: 'Can not move a shared document into a shared folder'},
    1100012: {fa: 'شرایط غیر منتظره', en: 'Unexpected condition'},
    1100013: {fa: 'نمی‌توان به پوشه‌ای که به اشتراک گذاشته شده بازگرداند', en: 'Can not restore into a shared folder'},
    1100014: {fa: 'نمی‌توان سندی که درون یک پوشه به اشتراک گذاشته شده است از اشتراک خارج کرد', en: 'Can not unshare a document which resides inside a shared folder'},
    1100015: {fa: 'کپی غیر مجاز است', en: 'Illegal copy'},
    1100016: {fa: 'این آیتم با کاربر انتخاب شده به اشتراک گذاشته شده است', en: 'Document has already been shared with selected user'},
    1100017: {fa: 'داخل آیتم انتخاب شده فایل یا پوشه به اشتراک گذاشته وجود دارد', en: 'There is a shared document iniside selected target'},
    1100018: {fa: 'تنها صاحب فایل می‌تواند آن را به اشتراک گذارد', en: 'Only owner can share items'},
    1100019: {fa: 'Download Center با این نام وجود دارد', en: 'Download Center already exists'},

    // beforeinsertuservalidator
    120001: {fa: 'کاربر وجود دارد', en: 'User Already Exists'},

    // beforeinsert
    120002: {fa: 'مدت زمان سرویس شما به اتمام رسیده است، لطفا جهت ادامه کار، اقدام به تمدید یا ارتقاء حساب خود نمایید', en: 'Your service is expired. To continue please upgrade or renew your account'},
    120003: {fa: 'فضای خالی ندارید', en: 'You haven\'t free space'},
    120004: {fa: 'پوشه وجود دارد', en: 'Folder Already Exists'},
    120005: {fa: 'فایل وجود دارد', en: 'File Already Exists'},
    120006: {fa: 'ایمیل وجود دارد', en: 'Email Already Exists'},

    // beforedeletedocumentvalidator
    120007: {fa: 'شما دسترسی لازم برای انجام این کار را ندارید', en: 'You are not authorized'},
    120008: {fa: 'شماره موبایل قبلا ثبت شده است', en: 'Mobile exists'},

    // wsComments
    130001: {fa: 'جایی به درستی مشخص نشده است', en: 'Where is not defined correctly'},

    // wsPublicAccessChildren
    130002: {fa: 'پارامتر مسیر غیر معتبر است‬‎', en: 'Invalid Path Param'},

    // wsDocumentsChildren
    130003: {fa: 'پارامتر مسیر غیر معتبر است‬‎', en: 'Invalid Path Param'},

    //
    130004: {fa: 'فایل دانلود شما آماده است', en: 'Your Download file Is Ready'},

    // upload
    140001: {fa: 'فایل وجود دارد', en: 'File exists'},
    140002: {fa: 'آپلود انجام شد', en: 'Done'},
    140003: {fa: 'آپلود ناموفق', en: 'Failed'},
    140004: {fa: 'آپلود وجود دارد', en: 'Existed'},
    140005: {fa: 'انصراف از آپلود', en: 'Canceled'},
    140006: {fa: 'کنترل ویروس', en: 'Virus checking'},
    140007: {fa: 'آپلود قبلا ایجاد شده است', en: 'Already exists'},
    140008: {fa: 'آپلود', en: 'Upload'},
    140009: {fa: 'فایل ویروسی', en: 'File Infected'},
    1400010: {fa: 'نمی‌توان به سایت مورد نظر متصل شد', en: 'Cannot resolve url'},
    1400011: {fa: 'آدرس وارد شده صحیح نیست', en: 'URL is not valid'},
    1400012: {fa: 'هیچ آدرسی تعریف نشده است', en: 'URL is not defined'},
    1400013: {fa: 'اتصال به این آدرس موفقیت‌آمیز نبود', en: 'Can not connect to host due Timeout'},
    1400014: {fa: 'انتقال فایل از آدرس مورد نظر به پنل ناموفق بود', en: 'Moving file to your panel failed'},
    1400015: {fa: 'سایز این آدرس اینترنتی بزرگتر از حد مجاز است', en: 'URL size is bigger than definde limitation'},
    1400016: {fa: 'این سرویس برای پلن‌های مجانی فعال نیست', en: 'As a free user , you cant use this service'},
    1400017: {fa: 'سایز این آدرس اینترنتی از حجم باقی‌مانده شما بیشتر است', en: 'URL size will exceed your quota'},
    1400018: {fa: 'سایز این آدرس اینترنتی مشخص نیست', en: 'Can not determine URL size'},
    1400019: {fa: 'آپلود این آدرس اینترنتی ممنوع است', en: 'Forbidden url inserted'},
    1400020: {fa: 'نمی‌توان از ادامه به کار این آدرس اینترنتی جلوگیری کرد', en: 'Cannot cancel URL stream'},
    1400021: {fa: 'مدت زمان سرویس شما به اتمام رسیده است، لطفا جهت ادامه کار، اقدام به تمدید یا ارتقاء حساب خود نمایید', en: 'Your service has expired, please renew or upgrade your account to continue working'},
    1400022: {fa: 'نمی‌توانید فایل در ریشه Download Center آپلود نمایید', en: 'Can not upload a file to download center root'},
    1400023: {fa: 'حجم فایل از حد مجاز پلن بیشتر می‌شود', en: 'File size exceeds the defined quota in your plan'},

    // Contact Group
    150001: {fa: 'گروه وجود دارد', en: 'Group already exists'},

    // Comment
    160001: {fa: 'ابتدا لاگین نمایید', en: ' Login required'},
    160002: {fa: 'فقط صاحب کامنت اجازه حذف آن را دارد', en: 'Only comment owner can delete it'},
    160003: {fa: 'خدمات غیر فعال است', en: 'Service is disabled'},
    160004: {fa: 'docId نمی‌تواند خالی باشد', en: 'DocId can not be empty*'},

    // balance
    170001: {fa: 'اعتبار برای خرید این فایل وجود ندارد', en: 'No balance to buy this file'},
    170002: {fa: 'اعتبار کافی برای خرید این فایل وجود ندارد', en: 'Not enough balance to buy this file'},
    170003: {fa: 'برای فروش نیست', en: 'Not for sale'},
    170004: {fa: 'فایل شما برای خودتان رایگان است', en: 'You can not buy your file, it\'s free for you'},
    170005: {fa: 'فایل قبلا خریداری شده', en: 'You have already purchased this item'},
    170006: {fa: 'ابتدا فایل را بخرید', en: 'You should buy this file first'},

    //
    1000036: {fa: 'امکان تغییر به پلن پایین‌تر وجود ندارد', en: 'You can not downgrade'},

    // Hosts
    180001: {fa: 'نام پلن اجباری است', en: 'Plan name is mandatory'},
    180002: {fa: 'نام دامنه اجباری است', en: 'Domain name is mandatory'},
    180003: {fa: 'هاست فعال با این دامنه در سیستم موجود است', en: 'Active host with domain name exist'},
    180004: {fa: 'کاربر فاکتور پرداخت نشده برای این پلن دارد', en: 'User has unpaid invoice for this plan'},
    180005: {fa: 'حذف هاست غیر مجاز است', en: 'Delete not allowed'},
    180006: {fa: 'پردازش با خطا مواجه شد', en: 'Retry not allowed'},
    180007: {fa: 'دامنه قبلا ثبت شده است', en: 'Domain is registered'},
    180008: {fa: 'تغییر رمز عبور با خطا روبرو شد', en: 'Change Password Exception'},
    180009: {fa: 'رمز عبور اجباری است', en: 'Password Is Mandatory'},
    1800010: {fa: 'نام دامنه معتبر نیست', en: 'Domain Name is not valid'},
    1800011: {fa: 'nic-handle اجباری است', en: 'Nic-hanlde in mandatory'},
    1800012: {fa: 'nic-handle نامعتبر است ', en: 'Invalid nic-hanlde'},

    // HostApi
    190001: {fa: 'خطا وجود دارد', en: 'Interrupted Exception occurred'},
    190002: {fa: 'خطا در اجرای عملیات', en: 'Execution Exception occurred'},
    190003: {fa: 'در زمان مناسب پاسخی دریافت نشد', en: 'Timeout Exception occurred'},

    // Domain
    200001: {fa: 'پردازش با خطا مواجه شد', en: 'Retry not allowed'},
    200002: {fa: 'حذف هاست غیر مجاز است', en: 'Delete not allowed'},
    200003: {fa: 'nic-handle اجباری است', en: 'Nic-hanlde in mandatory'},
    200004: {fa: 'nic-handle نامعتبر است ', en: 'Invalid nic-hanlde'},

    // DocLocation
    210001: {fa: 'فایلی انتخاب نشده است', en: 'Document id is mandatory'},
    210002: {fa: 'مقصد اجباری است', en: 'Location id is mandatory'},
    210003: {fa: 'url اجباری است', en: 'Url is mandatory'},

    // Admin
    220001: {fa: 'داده نامعتبر است', en: 'Invalid data'},
    220002: {fa: 'فایل مورد نظر وجود ندارد', en: 'File not found'},
    220003: {fa: 'شناسه نا معتبر است', en: 'Invalid id'},
    220004: {fa: 'وضعیت معتبر نیست', en: 'Invalid status'},
    220005: {fa: 'شناسه ضروری است', en: 'Id is required'},
    220006: {fa: 'گروه معتبر نیست', en: 'Invalid group'},

    // subdomain
    230001: {fa: 'پوشه معتبر نیست', en: 'Folder is not valid'},
    230002: {fa: 'دامنه با این نام قبلا ثبت شده است', en: 'Domain name exists'},
    230003: {fa: 'دامنه معتبر نیست', en: 'Domain name not valid'},
    230004: {fa: 'مسیر معتبر نیست', en: 'Path is not valid'},
    230005: {fa: 'پوشه باید انتخاب شود', en: 'Domain must be selected'},
    230006: {fa: 'اولین دامنه باید زیر دامنه پی جی  باشد', en: 'Fist domain must be pg'},
    230007: {fa: 'کاربر رایگان است', en: 'User plan is free'},
    230008: {fa: 'تعداد مجاز دامنه برای پلن کاربر یک دامنه است', en: 'One Domain Allowable for ProPlan'},
    230009: {fa: 'تعداد مجاز دامنه برای پلن کاربر پنج دامنه است', en: '5 Domain Allowable for PrePlan'},
    2300010: {fa: 'همنام پوشه موجود است', en: 'Folder name exists'},
    2300011: {fa: 'خطای داخلی', en: 'Json Data Problem'},
    2300012: {fa: 'نام کاربری اجباری است', en: 'Username is empty'},
    2300013: {fa: 'کلید اجباری است', en: 'Key is empty'},
    2300014: {fa: 'ثبت دامنه با خطا مواجه شد', en: 'Domain generating encountered a problem'},
    2300015: {fa: 'پوشه انتخابی باید خالی باشد', en: 'Folder must be empty'},
    2300016: {fa: 'حجم بیشتری مورد نیاز است', en: 'More quota is needed'},

    2300017: {fa: 'تعداد مجاز دامنه برای پلن کاربر یک دامنه دو باشد', en: 'The number of domain extensions for the user\'s plan is of a domain of two'},
    2300018: {fa: 'تعداد مجاز دامنه برای پلن کاربر یک دامنه سه باشد', en: 'The number of domain extensions for the user\'s plan is of a domain of three'},
    2300019: {fa: 'کاربر رایگان است', en: 'User is free'},
    2300020: {fa: 'دامنه با الیاس  قبلا ثبت شده است', en: 'Domain with alias is already registered'},
    2300021: {fa: 'نام دامنه طبق الگو نیست', en: 'Domain name is not matched with the pattern'},
    1000041: {fa: 'کاربر دو دامنه فعال دارد', en: 'User has two active domains'},
    1000042: {fa: 'کاربر سه دامنه فعال دارد', en: 'User has three active domains'},

    // invoice
    240001: {fa: 'نوع محصول اشتباه است', en: 'Incorrect Product Category'},
    240002: {fa: 'اعتبار کافی نیست', en: 'Insufficient Credit'},
    240003: {fa: 'شناسه اجباری است', en: 'ID is Mandatory'},
    240004: {fa: 'داده نا معتبر', en: 'Invalid ID'},
    240005: {fa: 'پلن نامعتبر', en: 'Invalid plan'},
    240006: {fa: 'کاربر احراز هویت نشده است', en: 'User is not authenticated'},
    240007: {fa: 'گروه ثبت نشده است', en: 'Group is not registered'},

    // promoCode
    250001: {fa: 'کد نامعتبر است', en: 'Not a valid code'},
    250002: {fa: 'تاریخ اعتبار کارت به اتمام رسیده است', en: 'Card expired'},
    250003: {fa: 'کارت برای خرید این محصول  نیست', en: 'Card not for dlc'},
    250004: {fa: 'کارت برای کاربر معتبر نیست', en: 'Card is not valid for the user'},
    250005: {fa: 'سقف اعتبار کارت به پایان رسیده است', en: 'The card credit limit has expired'},

    // purchase
    260001: {fa: 'download center نیست', en: 'Is not a download center'},
    260002: {fa: 'فایل منتشر نشده است', en: 'The file is not published'},

    // CfsPlanGroupUser
    270001: {fa: 'کاربر رایگان است', en: 'User is Free'},
    270002: {fa: 'هیج پلن تجاری وجود ندارد', en: 'There is no business plan'},
    270003: {fa: ' مشکل در پلن تجاری کاربر وجود دارد ', en: 'There is a problem in user\'s business plan'},
    270004: {fa: 'مشکل در تعریف پلن وجود دارد', en: 'There is a problem in defining plan'},
    270005: {fa: 'اجازه این عملیات داده نمی‌شود', en: 'This operation is not allowed'},
    270006: {fa: 'فقط مدیر اجازه این عملیات را دارد', en: 'Only Admin is allowed to do the operation'},
    270007: {fa: 'تعداد اعضا بیش از حد مجاز است', en: 'Member count exceeds the limit'},
    270008: {fa: 'خطا در تکراری بودن داده وجود دارد', en: 'Error in data repetition'},
    270009: {fa: 'مقدار وارد شده بیش از حجم مجاز مصرفی است', en: 'Entered value exceeds the limitation'},
    2700010: {fa: 'گروه نامعتبر است', en: 'Invalid Group'},
    2700011: {fa: 'ایمیل نامعتبر است', en: 'Invalid Email'},
    2700012: {fa: 'کاربر فعال است', en: 'User is active'},
    2700013: {fa: 'گروه با این مشخصات یافت نشد', en: 'Group with these specifications is not found'},
    2700014: {fa: 'اجازه پاک کردن داده نمی‌شود', en: 'Deletion is not allowed'},
    2700015: {fa: 'گروه نامعتبر است', en: 'Invalid Group'},
    2700016: {fa: 'خطا در اشتراک گذاری گروه وجود دارد', en: 'Error in sharing group'},
    2700017: {fa: 'ایمیل اشتراک گذاری درست نیست', en: 'Subscribed email is not correct'},
    2700018: {fa: 'گروه تعریف نشده است', en: 'Group is not defined'},
    2700019: {fa: 'گروه نامعتبر است', en: 'Invalid Group'},
    2700020: {fa: 'اجازه این عملیات داده نمی‌شود', en: 'Operation is not allowed'},
    2700021: {fa: 'کاربر تعریف نشده است', en: 'User is not defined'},
    2700022: {fa: 'کاربر نامعتبر است', en: 'Invalid User'},
    2700023: {fa: 'کاربر فعال نیست', en: 'User is not active'},
    2700024: {fa: 'خطا در سیستم وجود دارد', en: 'System Error'},
    2700025: {fa: 'کاربر قبلا ثبت نام شده است', en: 'User is already registered'},
    2700026: {fa: 'گروه با این مشخصات یافت نشد', en: 'Group with these specifications is not found'},
    2700027: {fa: 'گروه تعریف نشده است', en: 'Group is not defined'},
    2700028: {fa: 'داده‌ای وارد نشده است', en: 'No data is entered'},
    2700029: {fa: 'گروه فعال نیست', en: ''},
    2700030: {fa: 'صورتحساب پرداخت نشده است', en: ''},
    2700031: {fa: 'مقدار وارد شده مجاز نیست', en: 'Entered value is not allowed'},
    2700032: {fa: 'ایمیل وجود دارد', en: 'Email exists'},

    // CfsPlanGroup
    280001: {fa: 'کاربر باید مدیر باشد', en: 'User should be Admin'},
    280002: {fa: 'مدیر اجازه این عملیات را دارد', en: 'Admin owns the operation permission'},
    280003: {fa: 'محصول نامعتبر است', en: 'Product is not valid'},
    280004: {fa: 'این پلن تجاری نیست', en: 'This plan is not business'},
    280005: {fa: 'مشکل در پلن تجاری', en: 'Problem in business plan'},
    280006: {fa: 'خطا در تعریف پلن', en: 'Error in defining plan'},
    280007: {fa: 'مدیر از قبل پلن تعریف شده دارد', en: 'Admin already has a defined plan'},
    280008: {fa: 'اجازه ارتقا پلن وجود ندارد', en: 'Plan upgrade is not allowed'},
    280009: {fa: 'وضعیت تعریف نشده است', en: 'Status is not defined'},
    280010: {fa: 'پلن تعریف نشده است', en: 'Plan is not defined'},
    280011: {fa: 'کاربر وجود دارد', en: 'User exists'},
    280012: {fa: 'کاربر معتبر نیست', en: 'User is not valid'},
    280013: {fa: 'recurringPeriod ضروری است', en: 'RecurringPeriod is required'},

    // product
    290001: {fa: ' json-info اجباری است', en: 'Json-info is required'},
    290002: {fa: ' json-info درست نیست', en: 'Json-info is not valid'},
    290003: {fa: 'json-info در faname اجباری است', en: 'Faname in json-info is required'},
    290004: {fa: 'json-info در plan_type اجباری است', en: 'Plan_type in json-info is required'},
    290005: {fa: 'json-info در maximumSize اجباری است', en: 'MaximumSize in json-info is required'},
    290006: {fa: 'json-info در urlMaximumSize اجباری است', en: 'UrlMaximumSize in json-info is require'},
  },
}
export const getErrorMessage = (errorCode, errors, isCwsError, errorMessage) => {
  const key = isCwsError? 'CWS': 'CFS'
  const err = errors[key][errorCode][language.key]
  return err? capilizeString(err):
  errorMessage || errors[key][0][language.key]
}
